const REQUEST_ACTIVITIES = "REQUEST_ACTIVITIES"
const UPDATE_ACTIVITY = "UPDATE_ACTIVITY"
const ACTIVITIES_RECEIVED = "ACTIVITIES_RECEIVED"
const ACTIVITY_UPDATED = "ACTIVITY_UPDATED"
const CREATE_ACTIVITY = "CREATE_ACTIVITY"
const ACTIVITY_CREATED = "ACTIVITY_CREATED"
const DELETE_ACTIVITY = "DELETE_ACTIVITY"
const ACTIVITY_DELETED = "ACTIVITY_DELETED"

export {
  REQUEST_ACTIVITIES,
  UPDATE_ACTIVITY,
  ACTIVITIES_RECEIVED,
  ACTIVITY_UPDATED,
  CREATE_ACTIVITY,
  ACTIVITY_CREATED,
  DELETE_ACTIVITY,
  ACTIVITY_DELETED
}