const REQUEST_CONTACTS = "REQUEST_CONTACTS"
const UPDATE_CONTACT = "UPDATE_CONTACT"
const CONTACTS_RECEIVED = "CONTACTS_RECEIVED"
const CONTACT_UPDATED = "CONTACT_UPDATED"
const CREATE_CONTACT = "CREATE_CONTACT"
const CONTACT_CREATED = "CONTACT_CREATED"
const DELETE_CONTACT = "DELETE_CONTACT"
const CONTACT_DELETED = "CONTACT_DELETED"

export {
  REQUEST_CONTACTS,
  UPDATE_CONTACT,
  CONTACTS_RECEIVED,
  CONTACT_UPDATED,
  CREATE_CONTACT,
  CONTACT_CREATED,
  DELETE_CONTACT,
  CONTACT_DELETED
}