const REQUEST_NOTES = "REQUEST_NOTES"
const UPDATE_NOTE = "UPDATE_NOTE"
const NOTES_RECEIVED = "NOTES_RECEIVED"
const NOTE_UPDATED = "NOTE_UPDATED"
const CREATE_NOTE = "CREATE_NOTE"
const NOTE_CREATED = "NOTE_CREATED"
const DELETE_NOTE = "DELETE_NOTE"
const NOTE_DELETED = "NOTE_DELETED"

export {
  REQUEST_NOTES,
  UPDATE_NOTE,
  NOTES_RECEIVED,
  NOTE_UPDATED,
  CREATE_NOTE,
  NOTE_CREATED,
  DELETE_NOTE,
  NOTE_DELETED
}