const REQUEST_OPPORTUNITIES = "REQUEST_OPPORTUNITIES"
const UPDATE_OPPORTUNITY = "UPDATE_OPPORTUNITY"
const OPPORTUNITIES_RECEIVED = "OPPORTUNITIES_RECEIVED"
const OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED"
const CREATE_OPPORTUNITY = "CREATE_OPPORTUNITY"
const OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED"
const DELETE_OPPORTUNITY = "DELETE_OPPORTUNITY"
const OPPORTUNITY_DELETED = "OPPORTUNITY_DELETED"

export {
  REQUEST_OPPORTUNITIES,
  UPDATE_OPPORTUNITY,
  OPPORTUNITIES_RECEIVED,
  OPPORTUNITY_UPDATED,
  CREATE_OPPORTUNITY,
  OPPORTUNITY_CREATED,
  DELETE_OPPORTUNITY,
  OPPORTUNITY_DELETED
}